{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 2. Analysis of ragas evaluation\n",
    "\n",
    "Our criteria for a RAG evaluation framework are:\n",
    "- Comprehensibility\n",
    "- Reliability\n",
    "- Costs\n",
    "- Time\n",
    "\n",
    "Following we are going to analyse the RAGAs framework (open-source) based on the last three criteria.\n",
    "\n",
    "I am using the ragas_eval dataset as the golden dataset so I don't have to create one by my own and I can safe costs. \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from datasets import load_dataset\n",
    "\n",
    "ragas_eval = load_dataset('explodinggradients/fiqa', 'ragas_eval', split='baseline')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ragas.metrics import (\n",
    "    answer_relevancy,\n",
    "    answer_correctness,\n",
    "    context_recall,\n",
    "    context_relevancy\n",
    ")\n",
    "\n",
    "metrics = [answer_relevancy, answer_correctness, context_recall, context_relevancy]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- LLM-Judge temperatur = 0.0\n",
    "- Time of evaluation (10 runs) = 30 min\n",
    "- OpenAI Cost (10 runs) = 1.53$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [02:56<00:00,  1.47s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating:  68%|██████▊   | 82/120 [01:14<01:12,  1.90s/it]Task exception was never retrieved\n",
      "future: <Task finished name='Task-2621' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-2622' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Evaluating: 100%|██████████| 120/120 [02:50<00:00,  1.42s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [03:20<00:00,  1.67s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [02:39<00:00,  1.33s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [03:23<00:00,  1.70s/it]\n"
     ]
    }
   ],
   "source": [
    "from ragas import evaluate\n",
    "from langchain_openai import ChatOpenAI\n",
    "from langchain_openai import OpenAIEmbeddings\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "results_list = []\n",
    "\n",
    "for x in range(5):\n",
    "    result = evaluate(dataset=ragas_eval, llm=ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0.0), embeddings=OpenAIEmbeddings(model='text-embedding-3-small'), metrics=metrics, raise_exceptions=False)\n",
    "    results_list.append(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'answer_relevancy': 0.6444, 'answer_correctness': 0.4167, 'context_recall': 0.5882, 'context_relevancy': 0.2088}, {'answer_relevancy': 0.6147, 'answer_correctness': 0.4241, 'context_recall': 0.5834, 'context_relevancy': 0.2123}, {'answer_relevancy': 0.6120, 'answer_correctness': 0.4214, 'context_recall': 0.6342, 'context_relevancy': 0.2204}, {'answer_relevancy': 0.5452, 'answer_correctness': 0.3993, 'context_recall': 0.6210, 'context_relevancy': 0.1995}, {'answer_relevancy': 0.6447, 'answer_correctness': 0.4001, 'context_recall': 0.6270, 'context_relevancy': 0.2108}]\n"
     ]
    }
   ],
   "source": [
    "first_list = results_list\n",
    "print(first_list)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Here I am concatinating both lists so I have 10 evaluation result."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'answer_relevancy': 0.6415, 'answer_correctness': 0.4291, 'context_recall': 0.6311, 'context_relevancy': 0.2322}, {'answer_relevancy': 0.6128, 'answer_correctness': 0.4234, 'context_recall': 0.6043, 'context_relevancy': 0.2417}, {'answer_relevancy': 0.7066, 'answer_correctness': 0.4145, 'context_recall': 0.6098, 'context_relevancy': 0.2227}, {'answer_relevancy': 0.6504, 'answer_correctness': 0.4212, 'context_recall': 0.6397, 'context_relevancy': 0.1982}, {'answer_relevancy': 0.5812, 'answer_correctness': 0.4090, 'context_recall': 0.5699, 'context_relevancy': 0.2142}, {'answer_relevancy': 0.6444, 'answer_correctness': 0.4167, 'context_recall': 0.5882, 'context_relevancy': 0.2088}, {'answer_relevancy': 0.6147, 'answer_correctness': 0.4241, 'context_recall': 0.5834, 'context_relevancy': 0.2123}, {'answer_relevancy': 0.6120, 'answer_correctness': 0.4214, 'context_recall': 0.6342, 'context_relevancy': 0.2204}, {'answer_relevancy': 0.5452, 'answer_correctness': 0.3993, 'context_recall': 0.6210, 'context_relevancy': 0.1995}, {'answer_relevancy': 0.6447, 'answer_correctness': 0.4001, 'context_recall': 0.6270, 'context_relevancy': 0.2108}]\n"
     ]
    }
   ],
   "source": [
    "results_list = results_list + first_list\n",
    "print(results_list)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- LLM-Judge temperatur = 0.7\n",
    "- Time of evaluation (10 runs) = 33 min\n",
    "- OpenAI Cost (10 runs) = 1.28$"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating:   0%|          | 0/120 [00:00<?, ?it/s]Task exception was never retrieved\n",
      "future: <Task finished name='Task-3732' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3733' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3734' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3735' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3736' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3737' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3738' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-3739' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Evaluating: 100%|██████████| 120/120 [02:26<00:00,  1.22s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [03:49<00:00,  1.91s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [02:22<00:00,  1.19s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating:  99%|█████████▉| 119/120 [03:43<00:18, 18.25s/it]Failed to parse output. Returning None.\n",
      "Evaluating: 100%|██████████| 120/120 [04:42<00:00,  2.36s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [02:36<00:00,  1.30s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [03:23<00:00,  1.70s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating:  81%|████████  | 97/120 [01:43<00:57,  2.50s/it]Runner in Executor raised an exception\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/executor.py\", line 79, in _aresults\n",
      "    r = await future\n",
      "  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 571, in _wait_for_one\n",
      "    return f.result()  # May raise f.exception().\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/executor.py\", line 38, in sema_coro\n",
      "    return await coro\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/executor.py\", line 112, in wrapped_callable_async\n",
      "    return counter, await callable(*args, **kwargs)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/metrics/base.py\", line 116, in ascore\n",
      "    raise e\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/metrics/base.py\", line 112, in ascore\n",
      "    score = await self._ascore(row=row, callbacks=group_cm, is_async=is_async)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/metrics/_answer_correctness.py\", line 147, in _ascore\n",
      "    is_statement_present = await self.llm.generate(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/llms/base.py\", line 110, in generate\n",
      "    return await loop.run_in_executor(None, generate_text)\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/tenacity/__init__.py\", line 289, in wrapped_f\n",
      "    return self(f, *args, **kw)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/tenacity/__init__.py\", line 379, in __call__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/tenacity/__init__.py\", line 314, in iter\n",
      "    return fut.result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 451, in result\n",
      "    return self.__get_result()\n",
      "  File \"/usr/lib/python3.10/concurrent/futures/_base.py\", line 403, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/tenacity/__init__.py\", line 382, in __call__\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/ragas/llms/base.py\", line 139, in generate_text\n",
      "    return self.langchain_llm.generate_prompt(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 556, in generate_prompt\n",
      "    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 417, in generate\n",
      "    raise e\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 407, in generate\n",
      "    self._generate_with_cache(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py\", line 626, in _generate_with_cache\n",
      "    result = self._generate(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/langchain_openai/chat_models/base.py\", line 548, in _generate\n",
      "    response = self.client.create(messages=message_dicts, **params)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_utils/_utils.py\", line 275, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/resources/chat/completions.py\", line 581, in create\n",
      "    return self._post(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 1233, in post\n",
      "    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 922, in request\n",
      "    return self._request(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 998, in _request\n",
      "    return self._retry_request(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 1046, in _retry_request\n",
      "    return self._request(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 998, in _request\n",
      "    return self._retry_request(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 1046, in _retry_request\n",
      "    return self._request(\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/openai/_base_client.py\", line 1013, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.InternalServerError: <html>\n",
      "<head><title>502 Bad Gateway</title></head>\n",
      "<body>\n",
      "<center><h1>502 Bad Gateway</h1></center>\n",
      "<hr><center>cloudflare</center>\n",
      "</body>\n",
      "</html>\n",
      "Evaluating: 100%|██████████| 120/120 [03:00<00:00,  1.50s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating:   0%|          | 0/120 [00:00<?, ?it/s]Task exception was never retrieved\n",
      "future: <Task finished name='Task-5759' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-5760' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-5761' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-5762' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-5763' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-5764' coro=<AsyncClient.aclose() done, defined at /home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py:2011> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_client.py\", line 2018, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpx/_transports/default.py\", line 385, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_async/http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/httpcore/_backends/anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/streams/tls.py\", line 202, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"/home/dabr/code/langchain-rag-eval/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py\", line 1191, in aclose\n",
      "    self._transport.close()\n",
      "  File \"/usr/lib/python3.10/asyncio/selector_events.py\", line 706, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 753, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 515, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Evaluating: 100%|██████████| 120/120 [03:05<00:00,  1.55s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [03:26<00:00,  1.72s/it]\n",
      "passing column names as 'ground_truths' is deprecated and will be removed in the next version, please use 'ground_truth' instead. Note that `ground_truth` should be of type string and not Sequence[string] like `ground_truths`\n",
      "Evaluating: 100%|██████████| 120/120 [04:24<00:00,  2.20s/it]\n"
     ]
    }
   ],
   "source": [
    "from ragas import evaluate\n",
    "from langchain_openai import ChatOpenAI\n",
    "from langchain_openai import OpenAIEmbeddings\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "results_list_0_7 = []\n",
    "\n",
    "for x in range(10):\n",
    "    result = evaluate(dataset=ragas_eval, llm=ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0.0), embeddings=OpenAIEmbeddings(model='text-embedding-3-small'), metrics=metrics, raise_exceptions=False)\n",
    "    results_list_0_7.append(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'answer_relevancy': 0.6111, 'answer_correctness': 0.4209, 'context_recall': 0.6192, 'context_relevancy': 0.2184}, {'answer_relevancy': 0.5144, 'answer_correctness': 0.4248, 'context_recall': 0.5869, 'context_relevancy': 0.2225}, {'answer_relevancy': 0.5783, 'answer_correctness': 0.4071, 'context_recall': 0.6084, 'context_relevancy': 0.2164}, {'answer_relevancy': 0.6181, 'answer_correctness': 0.4263, 'context_recall': 0.6317, 'context_relevancy': 0.2075}, {'answer_relevancy': 0.6446, 'answer_correctness': 0.4244, 'context_recall': 0.5934, 'context_relevancy': 0.2031}, {'answer_relevancy': 0.6431, 'answer_correctness': 0.4137, 'context_recall': 0.6390, 'context_relevancy': 0.2690}, {'answer_relevancy': 0.2374, 'answer_correctness': 0.6440, 'context_recall': 0.4106, 'context_relevancy': 0.5698}, {'answer_relevancy': 0.5797, 'answer_correctness': 0.4094, 'context_recall': 0.6342, 'context_relevancy': 0.2192}, {'answer_relevancy': 0.5748, 'answer_correctness': 0.3989, 'context_recall': 0.6260, 'context_relevancy': 0.2270}, {'answer_relevancy': 0.5772, 'answer_correctness': 0.3924, 'context_recall': 0.5978, 'context_relevancy': 0.2232}]\n"
     ]
    }
   ],
   "source": [
    "print(results_list_0_7)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'results_list' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m answer_relevancy \u001b[38;5;241m=\u001b[39m [d[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124manswer_relevancy\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m d \u001b[38;5;129;01min\u001b[39;00m \u001b[43mresults_list\u001b[49m]\n\u001b[1;32m      2\u001b[0m answer_correctness \u001b[38;5;241m=\u001b[39m [d[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124manswer_correctness\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m d \u001b[38;5;129;01min\u001b[39;00m results_list]\n\u001b[1;32m      3\u001b[0m context_recall \u001b[38;5;241m=\u001b[39m [d[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcontext_recall\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;28;01mfor\u001b[39;00m d \u001b[38;5;129;01min\u001b[39;00m results_list]\n",
      "\u001b[0;31mNameError\u001b[0m: name 'results_list' is not defined"
     ]
    }
   ],
   "source": [
    "answer_relevancy = [d['answer_relevancy'] for d in results_list]\n",
    "answer_correctness = [d['answer_correctness'] for d in results_list]\n",
    "context_recall = [d['context_recall'] for d in results_list]\n",
    "context_relevancy = [d['context_relevancy'] for d in results_list]\n",
    "\n",
    "answer_relevancy_0_7 = [d['answer_relevancy'] for d in results_list_0_7]\n",
    "answer_correctness_0_7 = [d['answer_correctness'] for d in results_list_0_7]\n",
    "context_recall_0_7 = [d['context_recall'] for d in results_list_0_7]\n",
    "context_relevancy_0_7 = [d['context_relevancy'] for d in results_list_0_7]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Where are these deviations coming from?"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
